#!/usr/bin/env bash
# setxkbmap -option "grp:lwin_toggle,grp_led:scroll,ctrl:nocaps" -layout "us,ru,uz"
setxkbmap -option "grp:alt_shift_toggle,grp_led:scroll,ctrl:nocaps" -layout "us,ru,uz"
xautolock -time 11 -locker "gnome-screensaver-command -l" -notify 10   -notifier "notify-send -t 5000 -i gtk-dialog-info 'Locking in 10 seconds'" &
#guake &
yakuake &
empathy &
# tasque &
#deluge &

